#include<iostream>

using namespace std;

struct Aritheamatic
{
    int no1;
    int no2;
    
};


class Arithematic
{
    public:         
        int no1;
        int no2;

        Arithematic()
        {
            no1 = 0;
            no2 = 0;

        }

        Arithematic(int i, int j)
        {
            no1 = i;
            no2 = j;
        }


};

int main()
{

   Aritheamatic aobj1;
   Aritheamatic aobj2;

   aobj1.no1 = 0;
   aobj1.no1 = 0;

   aobj2.no1 = 10;
   aobj2.no1 = 11;



    return 0;
}